
name: Dispatch Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: write

jobs:
  test:
    uses: heons/test-workflow/.github/workflows/validate-pr-title.yml@master
    with:
      env: dev
