
name: Validate pr title

on:
  workflow_call:
    inputs:
      publish:
        description: 'Publish flag'
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          headerPattern: '^([\w\$\-]+)(\/([\w\$\-]+))?:(.*)$'
          headerPatternCorrespondence: type, scope, subject
